### ISSUE TITLE
Display button not working

### ISSUE THREAD

**Issue by Rachel10011** [nsmangat/nsmangat-COMP72070-Section1-Group3-EARNBankingSystem#10]
The bug is in the Qt ClientApp. Under the view statement page, the image does not display on the box after the display button is clicked. Meanwhile, the picture is still received on the ClientApp file.

**Comment by nsmangat** [comment]
Fixed by sending picture of bigger size. For some reason smaller pictures won't be displayed but larger pictures will.

Version: 1.0
