### ISSUE TITLE
Saving balance is loaded incorrectly

### ISSUE THREAD

**Issue by Rachel10011** [nsmangat/nsmangat-COMP72070-Section1-Group3-EARNBankingSystem#11]
The bug is in the view account balance page on the GUI. After logging in, the account balance of the chequing account is loaded correctly, but the saving account's balance is some weird number and is different every time and they are all similar to 6.312e^123. It could be because of the incorrect size of the send and recv packages between the client and server.

**Comment by nsmangat** [comment]
Fix: Found bug to be server side, problem with some basic arithmetic. Adjusted by adding and subtracting properly on server side based on type of transaction.

Version: 1.0
