### ISSUE TITLE
User information is not secured

### ISSUE THREAD

**Issue by Rachel10011** [nsmangat/nsmangat-COMP72070-Section1-Group3-EARNBankingSystem#12]
After creating a new account, user's information is not removed, all the filled fields in the signing in page stay the same so when the user goes back to that creating account page, they can still see it. After creating an account successfully, the user gets to log in right away without going through the login process.

**Comment by nsmangat** [comment]
Fix: Changed flow so after account create goes to login and clear fields after signup.

Version: 1.0
